# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-f3d1b4f6-3449-49b3-83a7-2c37753e6ffc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-f3d1b4f6-3449-49b3-83a7-2c37753e6ffc".device = "/dev/disk/by-uuid/f3d1b4f6-3449-49b3-83a7-2c37753e6ffc";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/63F8-8FF9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-4676696a-cd50-4fbc-913b-167246c1b9ff"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
